import os

SECRET_KEY = os.getenv('SECRET_KEY', 'my_secret_key_123')

DB_SERVER = 'DESKTOP-SI6G0B7'
DB_NAME = 'MercadoCruz'
DB_USER = 'RBLVOB01'
DB_PASSWORD = 'RPA123'

SQLALCHEMY_DATABASE_URI = f'mssql+pyodbc://{DB_USER}:{DB_PASSWORD}@{DB_SERVER}/{DB_NAME}?driver=ODBC+Driver+17+for+SQL+Server'

SQLALCHEMY_TRACK_MODIFICATIONS = False


