USE [master]
GO

/****** Object:  Database [MercadoCruz]    Script Date: 25/03/2024 19:01:59 ******/
CREATE DATABASE [MercadoCruz]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MercadoCruz', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MercadoCruz.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MercadoCruz_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MercadoCruz_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MercadoCruz].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MercadoCruz] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MercadoCruz] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MercadoCruz] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MercadoCruz] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MercadoCruz] SET ARITHABORT OFF 
GO

ALTER DATABASE [MercadoCruz] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MercadoCruz] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MercadoCruz] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MercadoCruz] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MercadoCruz] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MercadoCruz] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MercadoCruz] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MercadoCruz] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MercadoCruz] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MercadoCruz] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MercadoCruz] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MercadoCruz] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MercadoCruz] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MercadoCruz] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MercadoCruz] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MercadoCruz] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MercadoCruz] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MercadoCruz] SET RECOVERY FULL 
GO

ALTER DATABASE [MercadoCruz] SET  MULTI_USER 
GO

ALTER DATABASE [MercadoCruz] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MercadoCruz] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MercadoCruz] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MercadoCruz] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MercadoCruz] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MercadoCruz] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MercadoCruz] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MercadoCruz] SET  READ_WRITE 
GO


